### ISSUE TITLE
特别注意

### ISSUE THREAD

**Issue by negivup** [negivup/blog#3]
## 属性中的逗号不可省略

如果把属性中的逗号省略，就会编译成不可控的样式。

```styl
body
  font 12px Arial sans-seri
```

会编译成：

```css
body {
  font: 12px Arial sans-seri;
}
```

我们预期编译后的样式应该是：

```css
body {
  font: 12px Arial, sans-seri;
}
```

> 注意：属性中的逗号不要随意省略。
