### ISSUE TITLE
配置全局CSS

### ISSUE THREAD

**Issue by negivup** [negivup/blog#31]
# 配置全局CSS

**1.在*assets*中创建全局的CSS文件*css/global.css***

```css
body {
  background: red;
}
```

**2.在*nuxt.config.js*中配置全局CSS**

```js
  /*
  ** Global CSS
  */
  css: [
    '~/assets/css/global.css'
  ],
```

**3.运行项目，查看效果**

```bash
$ yarn dev
```
